name: app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      
      - name: Flutter version
        run: flutter --version

      - name: Install Flutter dependencies
        run: flutter pub get
      
      - name: Install Firebase
        run: npm install -g firebase-tools
      
      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      # Integration test, can only run on ubuntu-latest (not macOS or Windows)
      #- name: Run integration tests on Android emulator
      #  uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 29
      #    force-avd-creation: false
      #    emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
      #    disable-animations: true
      #    script: cd app; pwd; ls; firebase emulators:exec --only auth 'flutter test ./integration_test/int_test.dart'
