name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      
      - name: Flutter version
        run: flutter --version

      - name: Install app dependencies
        run: cd app && flutter pub get
      - name: Install web dependencies
        run: cd web && flutter pub get

      - name: Verify project formatting
        run: flutter format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: flutter analyze

      - name: Run app tests
        run: cd app && flutter test
      - name: Run web tests
        run: cd web && flutter test