
name: Flutter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      
      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: cd app && flutter pub get

      - name: Verify formatting
        run: cd app && flutter format --output=none --set-exit-if-changed .
        run: cd web && flutter format --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: cd app && flutter analyze
        run: cd web && flutter analyze

      - name: Run tests
        run: flutter test
