name: Flutter

on:
  push:
    branches: [main, web-my-farm]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # or: 'beta', 'dev' or 'master'

      - name: Flutter version
        run: flutter --version

      #- name: Install app dependencies
      #  run: cd app && flutter pub get
      #- name: Install web dependencies
      #  run: cd web && flutter pub get

      - name: Verify app formatting
        run: cd app && flutter format --output=none --set-exit-if-changed .
      - name: Verify web formatting
        run: cd web && flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze
